name: Public Npm

on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest

    name: 'publish npm'

    environment: npm

    steps:
      - uses: actions/checkout@master

      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
          # Specifies the registry, this field is required!
          registry-url: https://registry.npmjs.org/
      # clean install of your projects' deps. We use "npm ci" to avoid package lock changes
      - run: npm ci
      # set up git since we will later push to the repo
      - run: git config --global user.name "chasen_"
      - run: git config --global user.email "787025321@qq.com"
      # build the project
      - run: npm install
      # build the project
      - run: npm run build
      # publish to NPM -> there is one caveat, continue reading for the fix
      - run: npm publish
        env:
          # Use a token to publish to NPM. See below for how to set it up
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
