name: Public Npm
on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest

    name: 'publish npm'

    environment: npm

    steps:
      - uses: actions/checkout@master

      - name: Install and Build 
        run: |
          yarn install
          yarn run build

      - name: 发布到 NPM
        uses: actions/setup-node@v1
          with:
            node-version: 12
            registry-url: https://registry.npmjs.org/  # 设置发包 npm 地址仓库
        - run: npm publish # 执行发布
          env:
            NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}} # 刚刚设置的 NPM_TOKEN
